# .github/workflows/auto_send_polls.yml

name: Auto Send Telegram Polls

on:
  push:
    branches:
      - main
    paths:
      - 'questions.json'

  workflow_dispatch:

jobs:
  send-polls-job:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository Code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install Python Dependencies
        run: pip install -r requirements.txt

      # The 'run' step is now a single, simple command.
      # The loop, git commands, and '--batch-size' argument have been removed.
      - name: 4. Run Poll Sender Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          LOG_CHANNEL_ID: ${{ secrets.LOG_CHANNEL_ID }}
        run: python send_polls.py questions.json
