name: Auto Send Telegram Polls

on:
  # This action will trigger automatically on pushes to the main branch
  # ONLY if the questions.json file was changed.
  push:
    branches:
      - main
    paths:
      - 'questions.json' # Make sure this matches your file name

  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  send-polls-job:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository Code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install Python Dependencies
        run: pip install -r requirements.txt

      - name: 4. Run Poll Sender Script in a Loop
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          LOG_CHANNEL_ID: ${{ secrets.LOG_CHANNEL_ID }}
        run: |
          # This loop will continue running as long as progress is being made.
          while true; do
            # STEP A: Run the Python script for ONE batch of 50 items.
            # The script will send polls and update 'progress.json'.
            python send_polls.py questions.json --batch-size 50
            
            # STEP B: Check if the script made any progress.
            # `git diff --quiet` checks if the 'progress.json' file was changed.
            # If it was NOT changed, it means the script found no new polls to send.
            if git diff --quiet progress.json; then
              echo "✅ No changes in progress.json. All items have been sent. Exiting loop."
              break # This command exits the 'while' loop.
            fi
            
            # STEP C: If progress WAS made, save it for the next run.
            # We commit the updated 'progress.json' back to your repository.
            # The next iteration of the loop will use this updated file.
            echo "ℹ️ Progress was made. Committing 'progress.json' for the next batch."
            git config --global user.name 'GitHub Actions Bot'
            git config --global user.email 'actions-bot@github.com'
            git add progress.json
            git commit -m "Update poll progress"
            git push
          done
